import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
// import { auth } from "@/auth";
import Navbar from "@/components/common/Navbar";
import {AppWrapper} from "@/contexts";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const session = await auth();

  return (

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable}  overflow-x-hidden box-border antialiased`}
        >
          <AppWrapper>
            {/* <Navbar /> */}
            <Toaster />
            {children}
          </AppWrapper>
        </body>
      </html>

  );
}
